// <auto-generated />
// Generated by scripts/generateNugetLibrary.js. Do not edit generated SDK files by hand.

#nullable enable


namespace EmailsDone
{
    public sealed class EmailsDoneClientOptions
    {
        public string ApiBaseUrl { get; set; } = "https://api.emailsdone.dev";
    }
}
