// <auto-generated />
// Generated by scripts/generateNugetLibrary.js. Do not edit generated SDK files by hand.

#nullable enable


using System;
using System.Net;

namespace EmailsDone
{
    public sealed class EmailsDoneException : Exception
    {
        public EmailsDoneException(HttpStatusCode statusCode, string errorCode, string message, string responseBody)
            : base(message)
        {
            StatusCode = statusCode;
            ErrorCode = errorCode;
            ResponseBody = responseBody;
        }

        public HttpStatusCode StatusCode { get; }

        public string ErrorCode { get; }

        public string ResponseBody { get; }
    }
}
