// <auto-generated />
// Generated by scripts/generateNugetLibrary.js. Do not edit generated SDK files by hand.

#nullable enable


using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace EmailsDone
{
    public sealed class EmailsDoneClient : IDisposable
    {
        private static readonly JsonSerializerOptions JsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            WriteIndented = false
        };

        private readonly string _apiKey;
        private readonly HttpClient _httpClient;
        private readonly bool _disposeHttpClient;
        private readonly Uri _baseUri;

        private EmailsDoneClient(string apiKey, HttpClient? httpClient, EmailsDoneClientOptions? options)
        {
            if (string.IsNullOrWhiteSpace(apiKey))
            {
                throw new ArgumentException("An EmailsDone API key is required. Store it in server-side configuration, not frontend code.", nameof(apiKey));
            }

            _apiKey = apiKey;
            _httpClient = httpClient ?? new HttpClient();
            _disposeHttpClient = httpClient == null;
            _baseUri = normaliseBaseUri(options?.ApiBaseUrl ?? "https://api.emailsdone.dev");
            Send = new SendTemplates(this);
        }

        public SendTemplates Send { get; }

        public static EmailsDoneClient FromApiKey(string apiKey)
        {
            return new EmailsDoneClient(apiKey, null, null);
        }

        public static EmailsDoneClient FromApiKey(string apiKey, EmailsDoneClientOptions options)
        {
            return new EmailsDoneClient(apiKey, null, options);
        }

        public static EmailsDoneClient FromApiKey(string apiKey, HttpClient httpClient, EmailsDoneClientOptions? options = null)
        {
            return new EmailsDoneClient(apiKey, httpClient ?? throw new ArgumentNullException(nameof(httpClient)), options);
        }

        internal async Task<SendEmailResponse> SendTemplateAsync(
            string templateId,
            string to,
            IDictionary<string, object> data,
            SendEmailOptions? options,
            CancellationToken cancellationToken)
        {
            if (string.IsNullOrWhiteSpace(templateId))
            {
                throw new ArgumentException("Template id is required.", nameof(templateId));
            }

            if (string.IsNullOrWhiteSpace(to))
            {
                throw new ArgumentException("Recipient email address is required.", nameof(to));
            }

            var payload = new Dictionary<string, object>
            {
                ["templateId"] = templateId,
                ["to"] = to,
                ["data"] = data ?? throw new ArgumentNullException(nameof(data))
            };

            AddIfSet(payload, "templateVersion", options?.TemplateVersion);
            AddIfSet(payload, "from", options?.From);
            AddIfSet(payload, "fromName", options?.FromName);
            AddIfSet(payload, "replyTo", options?.ReplyTo);

            using (var request = new HttpRequestMessage(HttpMethod.Post, new Uri(_baseUri, "v1/send")))
            {
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);

                if (!string.IsNullOrWhiteSpace(options?.IdempotencyKey))
                {
                    request.Headers.Add("Idempotency-Key", options!.IdempotencyKey);
                }

                var json = JsonSerializer.Serialize(payload, JsonOptions);
                request.Content = new StringContent(json, Encoding.UTF8, "application/json");

                using (var response = await _httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false))
                {
                    var responseBody = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                    if (!response.IsSuccessStatusCode)
                    {
                        throw BuildException(response.StatusCode, responseBody);
                    }

                    var parsed = JsonSerializer.Deserialize<SendEmailResponse>(responseBody, JsonOptions);

                    if (parsed == null)
                    {
                        throw new EmailsDoneException(response.StatusCode, "invalid_response", "EmailsDone returned an empty or invalid response.", responseBody);
                    }

                    return parsed;
                }
            }
        }

        public void Dispose()
        {
            if (_disposeHttpClient)
            {
                _httpClient.Dispose();
            }
        }

        private static Uri normaliseBaseUri(string value)
        {
            if (!Uri.TryCreate(value, UriKind.Absolute, out var uri))
            {
                throw new ArgumentException("EmailsDone API base URL must be an absolute URL.", nameof(value));
            }

            var text = uri.ToString();
            return new Uri(text.EndsWith("/", StringComparison.Ordinal) ? text : text + "/");
        }

        private static void AddIfSet(IDictionary<string, object> payload, string key, string? value)
        {
            if (!string.IsNullOrWhiteSpace(value))
            {
                payload[key] = value!;
            }
        }

        private static EmailsDoneException BuildException(System.Net.HttpStatusCode statusCode, string responseBody)
        {
            try
            {
                var error = JsonSerializer.Deserialize<EmailsDoneErrorResponse>(responseBody, JsonOptions);
                var code = string.IsNullOrWhiteSpace(error?.Error) ? "api_error" : error!.Error!;
                var message = string.IsNullOrWhiteSpace(error?.Message) ? code : error!.Message!;
                return new EmailsDoneException(statusCode, code, message, responseBody);
            }
            catch (JsonException)
            {
                return new EmailsDoneException(statusCode, "api_error", "EmailsDone returned an error response.", responseBody);
            }
        }
    }
}
