// <auto-generated />
// Generated by scripts/generateNugetLibrary.js. Do not edit generated SDK files by hand.

#nullable enable


using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace EmailsDone
{
    public sealed class AuthenticationTemplates
    {
        private readonly EmailsDoneClient _client;

        internal AuthenticationTemplates(EmailsDoneClient client)
        {
            _client = client;
        }

        public Task<SendEmailResponse> AccountLockedAsync(string to, AccountLockedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("account-locked", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> EmailChangedAsync(string to, EmailChangedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("email-changed", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> LoginCodeAsync(string to, string code, LoginCodeOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(code))
            {
                throw new ArgumentException("code is required.", nameof(code));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "code", code);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("login-code", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> MagicLinkAsync(string to, string actionButtonUrl, MagicLinkOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("magic-link", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> MfaDisabledAsync(string to, MfaDisabledOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("mfa-disabled", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> MfaEnabledAsync(string to, MfaEnabledOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("mfa-enabled", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> NewDeviceLoginAsync(string to, NewDeviceLoginOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("new-device-login", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> PasswordChangedAsync(string to, PasswordChangedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("password-changed", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> PasswordResetAsync(string to, string actionButtonUrl, PasswordResetOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("password-reset", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> SuspiciousLoginAsync(string to, SuspiciousLoginOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("suspicious-login", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> VerifyEmailAsync(string to, string actionButtonUrl, VerifyEmailOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("verify-email", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> WelcomeAsync(string to, string actionButtonUrl, WelcomeOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("welcome", to, data, options, cancellationToken);
        }
    }

    public sealed class BillingTemplates
    {
        private readonly EmailsDoneClient _client;

        internal BillingTemplates(EmailsDoneClient client)
        {
            _client = client;
        }

        public Task<SendEmailResponse> CreditsExhaustedAsync(string to, string actionButtonUrl, CreditsExhaustedOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("credits-exhausted", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> CreditsLowAsync(string to, CreditsLowOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("credits-low", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> InvoiceAsync(string to, object invoice, string invoiceNumber, InvoiceOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (invoice == null)
            {
                throw new ArgumentNullException(nameof(invoice));
            }

            if (string.IsNullOrWhiteSpace(invoiceNumber))
            {
                throw new ArgumentException("invoiceNumber is required.", nameof(invoiceNumber));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "invoice", invoice);
            EmailsDoneRequestBuilder.Set(data, "invoiceNumber", invoiceNumber);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("invoice", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> InvoiceOverdueAsync(string to, string actionButtonUrl, InvoiceOverdueOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("invoice-overdue", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> PaymentFailedAsync(string to, string actionButtonUrl, PaymentFailedOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("payment-failed", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> PaymentSucceededAsync(string to, PaymentSucceededOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("payment-succeeded", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> RefundIssuedAsync(string to, RefundIssuedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("refund-issued", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> SubscriptionCancelledAsync(string to, SubscriptionCancelledOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("subscription-cancelled", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> SubscriptionPausedAsync(string to, SubscriptionPausedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("subscription-paused", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> SubscriptionRenewedAsync(string to, SubscriptionRenewedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("subscription-renewed", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> SubscriptionStartedAsync(string to, SubscriptionStartedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("subscription-started", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> TrialEndingAsync(string to, string actionButtonUrl, string trialEndDate, TrialEndingOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            if (string.IsNullOrWhiteSpace(trialEndDate))
            {
                throw new ArgumentException("trialEndDate is required.", nameof(trialEndDate));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "trialEndDate", trialEndDate);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("trial-ending", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> TrialStartedAsync(string to, TrialStartedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("trial-started", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> UsageThresholdAsync(string to, string message, UsageThresholdOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("usage-threshold", to, data, options, cancellationToken);
        }
    }

    public sealed class DeveloperTemplates
    {
        private readonly EmailsDoneClient _client;

        internal DeveloperTemplates(EmailsDoneClient client)
        {
            _client = client;
        }

        public Task<SendEmailResponse> ApiKeyCreatedAsync(string to, ApiKeyCreatedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("api-key-created", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ApiKeyRotatedAsync(string to, ApiKeyRotatedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("api-key-rotated", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ExportReadyAsync(string to, string actionButtonUrl, ExportReadyOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("export-ready", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> GenerationCompleteAsync(string to, string actionButtonUrl, GenerationCompleteOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("generation-complete", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ImportCompleteAsync(string to, ImportCompleteOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("import-complete", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> JobCompleteAsync(string to, JobCompleteOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("job-complete", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ProcessingFailedAsync(string to, ProcessingFailedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("processing-failed", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> QueuedRequestReadyAsync(string to, string actionButtonUrl, QueuedRequestReadyOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("queued-request-ready", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ReportReadyAsync(string to, string actionButtonUrl, ReportReadyOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("report-ready", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> UploadCompleteAsync(string to, UploadCompleteOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("upload-complete", to, data, options, cancellationToken);
        }
    }

    public sealed class NotificationTemplates
    {
        private readonly EmailsDoneClient _client;

        internal NotificationTemplates(EmailsDoneClient client)
        {
            _client = client;
        }

        public Task<SendEmailResponse> AnnouncementAsync(string to, string message, AnnouncementOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("announcement", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> DigestAsync(string to, DigestOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("digest", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> NotificationAlertAsync(string to, string message, NotificationAlertOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("notification-alert", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> NotificationInfoAsync(string to, string message, NotificationInfoOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("notification-info", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> NotificationSuccessAsync(string to, string message, NotificationSuccessOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("notification-success", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> NotificationWarningAsync(string to, string message, NotificationWarningOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("notification-warning", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ReminderAsync(string to, string message, ReminderOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("reminder", to, data, options, cancellationToken);
        }
    }

    public sealed class TeamTemplates
    {
        private readonly EmailsDoneClient _client;

        internal TeamTemplates(EmailsDoneClient client)
        {
            _client = client;
        }

        public Task<SendEmailResponse> ApprovalApprovedAsync(string to, string message, ApprovalApprovedOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("approval-approved", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ApprovalNeededAsync(string to, string actionButtonUrl, ApprovalNeededOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("approval-needed", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> ApprovalRejectedAsync(string to, string message, ApprovalRejectedOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(message))
            {
                throw new ArgumentException("message is required.", nameof(message));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "message", message);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("approval-rejected", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> InvitationAcceptedAsync(string to, InvitationAcceptedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("invitation-accepted", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> InvitedToWorkspaceAsync(string to, string actionButtonUrl, InvitedToWorkspaceOptions? options = null, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(actionButtonUrl))
            {
                throw new ArgumentException("actionButton.url is required.", nameof(actionButtonUrl));
            }

            var data = new Dictionary<string, object>();
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", actionButtonUrl);
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("invited-to-workspace", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> RoleChangedAsync(string to, RoleChangedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("role-changed", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> TeamMemberAddedAsync(string to, TeamMemberAddedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("team-member-added", to, data, options, cancellationToken);
        }

        public Task<SendEmailResponse> TeamMemberRemovedAsync(string to, TeamMemberRemovedOptions? options = null, CancellationToken cancellationToken = default)
        {
            var data = new Dictionary<string, object>();
            options?.ApplyTemplateData(data);

            return _client.SendTemplateAsync("team-member-removed", to, data, options, cancellationToken);
        }
    }

}
