// <auto-generated />
// Generated by scripts/generateNugetLibrary.js. Do not edit generated SDK files by hand.

#nullable enable


using System.Collections.Generic;

namespace EmailsDone
{
    public sealed class AccountLockedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public AccountLockedLockDetails? LockDetails { get; set; }

        public string? Notice { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "lockDetails", LockDetails);
            EmailsDoneRequestBuilder.Set(data, "notice", Notice);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class EmailChangedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public EmailChangedChangeDetails? ChangeDetails { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "changeDetails", ChangeDetails);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class LoginCodeOptions : SendEmailOptions
    {
        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? SecurityNote { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "securityNote", SecurityNote);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class MagicLinkOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class MfaDisabledOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Notice { get; set; }

        public string? Preheader { get; set; }

        public MfaDisabledSecurityDetails? SecurityDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "notice", Notice);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "securityDetails", SecurityDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class MfaEnabledOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Notice { get; set; }

        public string? Preheader { get; set; }

        public MfaEnabledSecurityDetails? SecurityDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "notice", Notice);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "securityDetails", SecurityDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class NewDeviceLoginOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public NewDeviceLoginLoginDetails? LoginDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "loginDetails", LoginDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class PasswordChangedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public PasswordChangedChangeDetails? ChangeDetails { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "changeDetails", ChangeDetails);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class PasswordResetOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public PasswordResetRequestDetails? RequestDetails { get; set; }

        public string? SecurityNote { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "requestDetails", RequestDetails);
            EmailsDoneRequestBuilder.Set(data, "securityNote", SecurityNote);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class SuspiciousLoginOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public SuspiciousLoginLoginDetails? LoginDetails { get; set; }

        public string? Notice { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "loginDetails", LoginDetails);
            EmailsDoneRequestBuilder.Set(data, "notice", Notice);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class VerifyEmailOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? SecurityNote { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "securityNote", SecurityNote);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class WelcomeOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? CallToActionHeading { get; set; }

        public string? CallToActionParagraph { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "callToActionHeading", CallToActionHeading);
            EmailsDoneRequestBuilder.Set(data, "callToActionParagraph", CallToActionParagraph);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class CreditsExhaustedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public CreditsExhaustedCreditDetails? CreditDetails { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "creditDetails", CreditDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class CreditsLowOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public CreditsLowCreditDetails? CreditDetails { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "creditDetails", CreditDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class InvoiceOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class InvoiceOverdueOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public InvoiceOverdueInvoiceDetails? InvoiceDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "invoiceDetails", InvoiceDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class PaymentFailedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionNote { get; set; }

        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public PaymentFailedPaymentDetails? PaymentDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionNote", ActionNote);
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "paymentDetails", PaymentDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class PaymentSucceededOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public PaymentSucceededPaymentDetails? PaymentDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "paymentDetails", PaymentDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class RefundIssuedOptions : SendEmailOptions
    {
        public string? FooterNote { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public RefundIssuedRefundDetails? RefundDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "footerNote", FooterNote);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "refundDetails", RefundDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class SubscriptionCancelledOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public SubscriptionCancelledSubscriptionDetails? SubscriptionDetails { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "subscriptionDetails", SubscriptionDetails);
        }
}

    public sealed class SubscriptionPausedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public SubscriptionPausedSubscriptionDetails? SubscriptionDetails { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "subscriptionDetails", SubscriptionDetails);
        }
}

    public sealed class SubscriptionRenewedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public SubscriptionRenewedSubscriptionDetails? SubscriptionDetails { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "subscriptionDetails", SubscriptionDetails);
        }
}

    public sealed class SubscriptionStartedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public SubscriptionStartedSubscriptionDetails? SubscriptionDetails { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "subscriptionDetails", SubscriptionDetails);
        }
}

    public sealed class TrialEndingOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public string? UpgradeNote { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "upgradeNote", UpgradeNote);
        }
}

    public sealed class TrialStartedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public TrialStartedTrialDetails? TrialDetails { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "trialDetails", TrialDetails);
        }
}

    public sealed class UsageThresholdOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public UsageThresholdUsageDetails? UsageDetails { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "usageDetails", UsageDetails);
        }
}

    public sealed class ApiKeyCreatedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public ApiKeyCreatedApiKeyDetails? ApiKeyDetails { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Notice { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "apiKeyDetails", ApiKeyDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "notice", Notice);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ApiKeyRotatedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public ApiKeyRotatedApiKeyDetails? ApiKeyDetails { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "apiKeyDetails", ApiKeyDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ExportReadyOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public ExportReadyExportDetails? ExportDetails { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "exportDetails", ExportDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class GenerationCompleteOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public GenerationCompleteGenerationDetails? GenerationDetails { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "generationDetails", GenerationDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ImportCompleteOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public ImportCompleteImportDetails? ImportDetails { get; set; }

        public string? Message { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "importDetails", ImportDetails);
            EmailsDoneRequestBuilder.Set(data, "message", Message);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class JobCompleteOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public JobCompleteJobDetails? JobDetails { get; set; }

        public string? Message { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "jobDetails", JobDetails);
            EmailsDoneRequestBuilder.Set(data, "message", Message);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ProcessingFailedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Message { get; set; }

        public string? Preheader { get; set; }

        public ProcessingFailedProcessingDetails? ProcessingDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "message", Message);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "processingDetails", ProcessingDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class QueuedRequestReadyOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public QueuedRequestReadyRequestDetails? RequestDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "requestDetails", RequestDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ReportReadyOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public ReportReadyReportDetails? ReportDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "reportDetails", ReportDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class UploadCompleteOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Message { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public UploadCompleteUploadDetails? UploadDetails { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "message", Message);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "uploadDetails", UploadDetails);
        }
}

    public sealed class AnnouncementOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class DigestOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Message { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        public decimal? SummaryAlerts { get; set; }

        public decimal? SummaryNewItems { get; set; }

        public decimal? SummaryUpdates { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "message", Message);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
            EmailsDoneRequestBuilder.Set(data, "summary.alerts", SummaryAlerts);
            EmailsDoneRequestBuilder.Set(data, "summary.newItems", SummaryNewItems);
            EmailsDoneRequestBuilder.Set(data, "summary.updates", SummaryUpdates);
        }
}

    public sealed class NotificationAlertOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public NotificationAlertAlertDetails? AlertDetails { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "alertDetails", AlertDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class NotificationInfoOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class NotificationSuccessOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class NotificationWarningOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ReminderOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public ReminderReminderDetails? ReminderDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "reminderDetails", ReminderDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ApprovalApprovedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public ApprovalApprovedApprovalDetails? ApprovalDetails { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "approvalDetails", ApprovalDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ApprovalNeededOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public ApprovalNeededApprovalDetails? ApprovalDetails { get; set; }

        public string? Heading { get; set; }

        public string? Message { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "approvalDetails", ApprovalDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "message", Message);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class ApprovalRejectedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public ApprovalRejectedApprovalDetails? ApprovalDetails { get; set; }

        public string? Heading { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "approvalDetails", ApprovalDetails);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class InvitationAcceptedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public InvitationAcceptedInviteDetails? InviteDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "inviteDetails", InviteDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class InvitedToWorkspaceOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public InvitedToWorkspaceInviteDetails? InviteDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "inviteDetails", InviteDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class RoleChangedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public string? Preheader { get; set; }

        public RoleChangedRoleDetails? RoleDetails { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "roleDetails", RoleDetails);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class TeamMemberAddedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public TeamMemberAddedMemberDetails? MemberDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "memberDetails", MemberDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

    public sealed class TeamMemberRemovedOptions : SendEmailOptions
    {
        public string? ActionButtonLabel { get; set; }

        public string? ActionButtonUrl { get; set; }

        public string? Heading { get; set; }

        public string? Intro { get; set; }

        public TeamMemberRemovedMemberDetails? MemberDetails { get; set; }

        public string? Preheader { get; set; }

        public string? Subject { get; set; }

        internal override void ApplyTemplateData(IDictionary<string, object> data)
        {
            EmailsDoneRequestBuilder.Set(data, "actionButton.label", ActionButtonLabel);
            EmailsDoneRequestBuilder.Set(data, "actionButton.url", ActionButtonUrl);
            EmailsDoneRequestBuilder.Set(data, "heading", Heading);
            EmailsDoneRequestBuilder.Set(data, "intro", Intro);
            EmailsDoneRequestBuilder.Set(data, "memberDetails", MemberDetails);
            EmailsDoneRequestBuilder.Set(data, "preheader", Preheader);
            EmailsDoneRequestBuilder.Set(data, "subject", Subject);
        }
}

}
