// <auto-generated />
// Generated by scripts/generateNugetLibrary.js. Do not edit generated SDK files by hand.

#nullable enable


using System.Collections.Generic;

namespace EmailsDone
{
    public class SendEmailOptions
    {
        public string? TemplateVersion { get; set; }

        public string? From { get; set; }

        public string? FromName { get; set; }

        public string? ReplyTo { get; set; }

        public string? IdempotencyKey { get; set; }

        internal virtual void ApplyTemplateData(IDictionary<string, object> data)
        {
        }
    }
}
