// <auto-generated />
// Generated by scripts/generateNugetLibrary.js. Do not edit generated SDK files by hand.

#nullable enable


namespace EmailsDone
{
    public sealed class SendTemplates
    {
        public AuthenticationTemplates Authentication { get; }
        public BillingTemplates Billing { get; }
        public DeveloperTemplates Developer { get; }
        public NotificationTemplates Notification { get; }
        public TeamTemplates Team { get; }

        internal SendTemplates(EmailsDoneClient client)
        {
            Authentication = new AuthenticationTemplates(client);
            Billing = new BillingTemplates(client);
            Developer = new DeveloperTemplates(client);
            Notification = new NotificationTemplates(client);
            Team = new TeamTemplates(client);
        }
    }
}
